import ClipperLib from "clipper-lib";

const SCALE = 100;
const toClipper = (paths) => paths.map((path) =>
  path.map(({ x, y }) => ({ X: Math.round(x * SCALE), Y: Math.round(y * SCALE) })),
);
const fromClipper = (paths) => paths.map((path) =>
  path.map(({ X, Y }) => ({ x: X / SCALE, y: Y / SCALE })),
);

/** Turns a brush or eraser centre line into its actual painted area. */
export function roundStrokePolygon(points, width) {
  if (!points.length || width <= 0) return [];
  const offset = new ClipperLib.ClipperOffset(2, 0.2 * SCALE);
  const path = toClipper([points])[0];
  if (path.length === 1) path.push({ X: path[0].X + 1, Y: path[0].Y });
  offset.AddPath(path, ClipperLib.JoinType.jtRound, ClipperLib.EndType.etOpenRound);
  const result = new ClipperLib.Paths();
  offset.Execute(result, width * SCALE / 2);
  return fromClipper(result);
}

/** Subtracts the eraser area from filled vector geometry, including holes. */
export function subtractPolygons(subject, eraser) {
  if (!subject.length || !eraser.length) return subject;
  const clipper = new ClipperLib.Clipper();
  clipper.AddPaths(toClipper(subject), ClipperLib.PolyType.ptSubject, true);
  clipper.AddPaths(toClipper(eraser), ClipperLib.PolyType.ptClip, true);
  const result = new ClipperLib.Paths();
  clipper.Execute(
    ClipperLib.ClipType.ctDifference,
    result,
    ClipperLib.PolyFillType.pftEvenOdd,
    ClipperLib.PolyFillType.pftEvenOdd,
  );
  return fromClipper(result);
}

export function polygonsToPathD(paths) {
  return paths.map((path) =>
    path.length < 3 ? "" :
      `M ${path.map(({ x, y }) => `${Number(x.toFixed(2))} ${Number(y.toFixed(2))}`).join(" L ")} Z`,
  ).filter(Boolean).join(" ");
}

/** Reads paths previously generated by polygonsToPathD. */
export function pathDToPolygons(d) {
  return [...d.matchAll(/M\s+([^Z]+)Z/gi)].map(([, body]) => {
    const numbers = body.match(/-?\d+(?:\.\d+)?(?:e[+-]?\d+)?/gi)?.map(Number) || [];
    const path = [];
    for (let i = 0; i < numbers.length; i += 2) {
      path.push({ x: numbers[i], y: numbers[i + 1] });
    }
    return path;
  }).filter((path) => path.length >= 3);
}

export function polygonArea(paths) {
  return Math.abs(toClipper(paths).reduce((sum, path) =>
    sum + ClipperLib.Clipper.Area(path), 0)) / (SCALE * SCALE);
}
